### PR TITLE
fixes bugs in interactive reporting

### PR DESCRIPTION
**Pull request by piguy314159265**

### CODE REVIEW

**Comment by ramnathv** [comment]
@piguy314159265 The `flightdeck` package was moved to `Suggests` so that we dont create a circular dependency between Alteryx packages. Can you please revert the changes where you moved them back to `Imports`? This will result in some NOTES on R CMD CHECK, but they are just NOTES and we can ignore them safely.

**Comment by piguy314159265** [comment]
Thanks @ramnathv . This is now done (https://github.com/alteryx/AlteryxPredictive/pull/59/commits/94c731603af12754eea1c17d346a76cd5a69c2cc and https://github.com/alteryx/AlteryxPredictive/pull/59/commits/d5c9c2e35c9b00a4259346caf3962f98e574890b)

**Comment by ramnathv** [comment]
Thanks @piguy314159265. One last thing to be done to get things to work correctly is to put the `requireNamespace("flightdeck")` call back in `interactive_lm_report`. This is required for the package to be loaded before the dashboard related functions are run.

**Comment by piguy314159265** [comment]
resolved here: https://github.com/alteryx/AlteryxPredictive/pull/60

**Pull request merged**
